## 287. Introduction
- You'll learn and use `NumPy` module
- NumPy comes with various in-built classes and functions that will help us do calculations and also manipulate single-dimensional arrays as well as multi-dimensional arrays
- All the elements in a NumPy array are of same type
- To use the NumPy module, we install it first and then we simply import NumPy, and start using it
- We'll create arrays using various functions that NumPy provides like `array()`, `linspace()`, `logspace()`, `arange()`, `zeros()`, `ones()`, and more
- And, then we'll also use various mathematical opertations that are in-built into NumPy
- This will help you do various scientific calculations as well
- We'll also compare arrays, do array copying, slicing of arrays, deal with multi-dimensional arrays, matrics and much more
- Once you are aware of all these, you can learn other things in NumPy as required for your projects

## 288. NumPy in action
- You'll learn how to work with arrays using the NumPy package
- `numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`
    - Creates an array
    - returns ndarray, an array object satisfying the specified requirements
    - `object` : array-like, an array, any object exposing the array interface, an object whose ``__array__`` method returns an array or any (nested) sequence. If object is a scalar, a 0-dimensional array containing object is returned
    - `dtype` : datatype, optional, the desired data-type for the array. If not given, NumPy will try to use a default ``dtype`` that can represent the values (by applying promotion rules when necessary)

In [1]:
# numpyinaction
# arrays.py
import numpy

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
print(arr)

[1 2 3 4 5]


In [4]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
carr = array(['a', 'b', 'c']) # character arrray
print(arr)
print(carr)

[1 2 3 4 5]
['a' 'b' 'c']


In [5]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest']) # string array
print(arr)
print(carr)
print(sarr)

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']


In [6]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']


## 289. linspace logspace and more
- Previously, we've learned how to create and use arrays using NumPy `array()` function
- Now, we'll learn a few more functions to create arrays and these functions will fill in the array with certain values that are calculated
- `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0,)`
    - return evenly spaced numbers over a specified interval
    - returns ndarray, there are `num` equally spaced samples in the closed interval ``[start, stop]`` or the half-open interval ``[start, stop)`` (depending on whether `endpoint` is True or False)
    - the endpoint of the interval can optionally be excluded

In [7]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100, 50));

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [8]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100, 20));

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [9]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(1, 100, 50));

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [10]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)); # default step is 50

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


- `numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`
    - return numbers spaced evely on a log scale
    - in linear space, the sequence starts at ``base ** start`` (`base` to the power of `start`) and ends with ``base ** stop``

In [11]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)); # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [12]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
for i in larr:
    print(i)

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
10.0
24.42053094548651
59.63623316594643
145.63484775012444
355.64803062231283
868.511373751352
2120.9508879201903
5179.474679231213
12648.552168552958
30888.435964774784
75431.20063354608
184206.99693267164
449843.2668969444
1098541.1419875573
2682695.7952797273
6551285.568595509

- `numpy.arange([start, ]stop[, step], dtype=None, *, like=None)`
    - array-range, takes three values, the first two values are required being start & stop, and last one is step which is optional
    - return evenly spaced values within a given interval
    - for integer arguments, this function is roughly equivalent to Python in-built :py:class:`range`, but returns an ndarray rather than a ``range`` instance
    - when using a non-integer step such as 0.1, it is often better to use `numpy.linspace`
    - for floating point arguments, the length of the result is ``ceil((stop - start)/step)`` , Because of floating point overflow, this rule may result in the last element of `out` being greater than `stop`
    - `Warning` The length of output might not be numerically stable

In [13]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(1, 5))

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

In [14]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(1, 20))

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

In [15]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(1, 20, 2)) # with step

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

In [16]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(100, 1, -1)) # reverse / decrement

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

- `numpy.zeros(shape, dtype=float, order='C', *, like=None)`
    - out:`ndarray`, return a new array of given shape & type, filled with zeros
    - `shape` : int or tuple of ints, shape of the new array e.g. `(2, 3)` or `2`
    - `dtype` : datatype, optional, the desired data-type for the array. e.g. `numpy.int8` , default is `numpy.float64`
    - `order` : {'C', 'F'}, optional, default: 'C', whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory
    - `like` : array_like, optional
        - Reference object to allow the creation of NumPy arrays
        - If an array-like passed in as ``like`` supports the ``__array_function__`` protocol, the result will be defined by it
        - in this case, it ensures the creation of an array object compatible with that passed in via this argument

In [17]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(100, 1, -1)) # reverse / decrement
print(zeros(20)) # returns ndarray filled with zeros in specified shape

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

- `numpy.ones(shape, dtype=None, order='C', *, like=None)`
    - out:`ndarray`, return a new array of given shape and type, filled with ones
    - `shape` : int or tuple of ints, shape of the new array e.g. `(2, 3)` or `2`
    - `dtype` : datatype, optional, the desired data-type for the array. e.g. `numpy.int8` , default is `numpy.float64`
    - `order` : {'C', 'F'}, optional, default: 'C', whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory
    - `like` : array_like, optional
        - Reference object to allow the creation of NumPy arrays
        - If an array-like passed in as ``like`` supports the ``__array_function__`` protocol, the result will be defined by it
        - in this case, it ensures the creation of an array object compatible with that passed in via this argument

In [18]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

print(linspace(0, 100)) # default step is 50
larr = logspace(1, 20) # default step is 50, default base is 10.0
# for i in larr:
#     print(i)
print(larr)
print(arange(100, 1, -1)) # reverse / decrement
print(zeros(20)) # returns ndarray filled with zeros in specified shape
print(ones(10)) # returns ndarray filled with ones in specified shape

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[1.00000000e+01 2.44205309e+01 5.96362332e+01 1.45634848e+02
 3.55648031e+02 8.68511374e+02 2.12095089e+03 5.17947468e+03
 1.26485522e+04 3.08884360e+04 7.54312006e+04 1.84206997e+05
 4.49843267e+05 1.09854114e+06 2.68269580e+06 6.55128557e+06
 1.59985872e+07 3.90693994e+07 9.5409

## 290. Using math functions
- You'll learn certain mathematical functions that NumPy provides out-of-the-box, so that we can apply them on an array or multiple arrays

In [19]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays

[11 13 15 17]


In [20]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element

[11 13 15 17]
[-1  0  1  2]


In [21]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [22]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
print(log(a1)) # log of all the elements

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [23]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
2.5


In [24]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, -4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1))# absolute values' array

[11 13 15  9]
[-1  0  1 -6]
[0.84147098 0.90929743 0.14112001 0.7568025 ]
0.5
[1 2 3 4]


In [25]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, -4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array

[11 13 15  9]
[-1  0  1 -6]
[0.84147098 0.90929743 0.14112001 0.7568025 ]
0.5
[1 2 3 4]
-4


In [26]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, -4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array
print(max(a1)) # mamximum value from elements of array

[11 13 15  9]
[-1  0  1 -6]
[0.84147098 0.90929743 0.14112001 0.7568025 ]
0.5
[1 2 3 4]
-4
3


In [27]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array
print(max(a1)) # mamximum value from elements of array
print(pow(a1, 2)) # power 2 of each element
print(pow(2, a1)) # power of array a1 to base 2

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
2.5
[1 2 3 4]
1
4
[ 1  4  9 16]
[ 2  4  8 16]


In [28]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array
print(max(a1)) # mamximum value from elements of array
print(pow(a1, 2)) # power 2 of each element
print(pow(2, a1)) # power of array a1 to base 2
print(sqrt(a1)) # square-root of each element

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
2.5
[1 2 3 4]
1
4
[ 1  4  9 16]
[ 2  4  8 16]
[1.         1.41421356 1.73205081 2.        ]


In [29]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array
print(max(a1)) # mamximum value from elements of array
print(pow(a1, 2)) # power 2 of each element
print(pow(2, a1)) # power of array a1 to base 2
print(sqrt(a1)) # square-root of each element
print(exp(a1)) # exponent value of each element

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
2.5
[1 2 3 4]
1
4
[ 1  4  9 16]
[ 2  4  8 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [30]:
# mathfunctions.py
from numpy import *

a1 = array([1, 2, 3, 4])
a2 = array([10, 11, 12, 13])
print(a1 + a2) # adds two arrays
print(a1 - 2) # broadcasting operation, subtracts 2 from every element
print(sin(a1)) # sin function is applied to all the elements
# print(log(a1)) # log of all the elements
print(mean(a1)) # mean of all the elements
print(abs(a1)) # absolute values' array
print(min(a1)) # minimum value from elements of array
print(max(a1)) # mamximum value from elements of array
print(pow(a1, 2)) # power 2 of each element
print(pow(2, a1)) # power of array a1 to base 2
print(sqrt(a1)) # square-root of each element
print(exp(a1)) # exponent value of each element
print(sum(a2)) # sum of all elements of a1

[11 13 15 17]
[-1  0  1  2]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
2.5
[1 2 3 4]
1
4
[ 1  4  9 16]
[ 2  4  8 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
46


## 291. Array Comparison
- We'll learn how to comapre two arrays with same number of elements in NumPy
- it compares every element of one array with eavery corresponding element of another array

In [31]:
# comparison.py
from numpy import *

a1 = array([10, 30, 50, 70, 90])
a2 = array([20, 40, 60, 80, 100])

print(a1>a2)

[False False False False False]


In [32]:
from numpy import *

a1 = array([10, 30, 50, 70, 90])
a2 = array([20, 40, 60, 80, 100])

print(a1>a2)
print(a1<a2)

[False False False False False]
[ True  True  True  True  True]


In [33]:
from numpy import *

a1 = array([10, 30, 50, 70, 110]) # changed one element
a2 = array([20, 40, 60, 80, 100])

print(a1>a2)
print(a1<a2)

[False False False False  True]
[ True  True  True  True False]


In [34]:
from numpy import *

a1 = array([10, 30, 50, 70, 100]) # changed one element again
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

[False False False False False]
[ True  True  True  True False]
[False False False False  True]


- `any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)`
    - Test whether any array element along a given axis evealuates to True
    - returns single boolean if `axis` is ``None``
    - returns, any : bool or ndarray , a new boolean or `ndarray ` is returned unless `out` is specified, in which case a reference to `out` is returned
    - `a` : array_like, input array or object that can be conerted to an array
    - `axis` : None or int or tuple of ints, optional
        - axis or axes along which a logical OR reduction is performed
        - The default (``axis=None``) is to perform a logical OR over all the dimensions of the input array
        - `axis` may be negative, in which case it counts from the last to the first axis

In [35]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True


- `all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)`
    - Test whether all array elements alonga  given axis evaluate to True
    - returns all: ndarray or bool, a new boolean or array is returned unless `out` is specified, in which case a reference to `out` is returned
    - `a` : array_like, input array or object that can be conerted to an array
    - `axis` : None or int or tuple of ints, optional
        - axis or axes along which a logical OR reduction is performed
        - The default (``axis=None``) is to perform a logical OR over all the dimensions of the input array
        - `axis` may be negative, in which case it counts from the last to the first axis

In [36]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False


In [37]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(all(a1 <= a2))

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True


In [38]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True


## 292. More Comparison Functions
- You'll learn three more array comparison functions provided by NumPy
- These functions take multiple conditions and checks if each element in an array follows these conditions
- `numpy.logical_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`
    - compute the truth value of `x1` AND `x2` element-wise
    - returns `y` : ndarray or bool
        - boolean result of the logical AND operation applied to the elements of `x1` and `x2`, the shape is determined by broadcasting
        - This is a scalar if both `x1` and `x2` are scalars
    - `x1`, `x2` : array_like, input arrays
        - if ``x1.shape!=x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output)
    - `out` : ndarray, None, or tuple of ndarray and None, optional
        - a location into which the result is stored, If provided, it must have a shape that the inputs broadcast to. If not provided or None, a freshly allocated array is returned. A tuple (possible only as an keyword argument) must have length equal to the number of outputs
    - `where` : array_like, optional
        - This condition is broadcast over the input. At locations where the condition is True, the `out` array will be set to ufunc result
        - Elsewhere, the `out` array, will retain its original value
        - Note that if an uninitialized `out` array is created via the default ``out=None``, locations within it where the condition is False will remain uninitialized
    - The ``&`` operator can be used as a shorthand for ``numpy.logical_and`` on
boolean ndarrays.

In [39]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True
[False  True  True  True  True]


In [40]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 >= 10, a1 < 101)) # changed first condition

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True
[ True  True  True  True  True]


- `numpy.logical_or(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`
    - compute the truth value of `x1` OR `x2` element-wise
    - returns `y` : ndarray or bool
        - Boolean result of the logical OR operation applied to the elements of `x1` and `x2`; the shape is determined by broadcasting.
        - This is a scalar if both `x1` and `x2` are scalars.
    - `x1`, `x2` : array_like
        - Logical OR is applied to the elements of `x1` and `x2`.
        - If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
    - `out` : ndarray, None, or tuple of ndarray and None, optional
        - A location into which the result is stored.
        - If provided, it must have a shape that the inputs broadcast to. If not provided or None, a freshly-allocated array is returned. A tuple (possible only as a keyword argument) must have length equal to the number of outputs.
    - `where` : array_like, optional
        - This condition is broadcast over the input. At locations where the condition is True, the `out` array will be set to the ufunc result.
        - Elsewhere, the `out` array will retain its original value.
        - Note that if an uninitialized `out` array is created via the default ``out=None``, locations within it where the condition is False will remain uninitialized.
    - The ``|`` operator can be used as a shorthand for ``numpy.logical_or`` on
boolean ndarrays.

In [41]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True
[False  True  True  True  True]
[ True  True  True  True  True]


- `numpy.logical_not(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`
    - Compute the truth value of NOT `x` element-wise
    - returns `y` : bool or ndarray of bool
        - boolean result with the same shape as `x` of the NOT operation on elements of `x`
        - This is a scalar if `x` is scalar
    - `x` : array_like
        - Logical NOT is applied to the elements of `x`
    - `out` : ndarray, None or tuple of ndarray and None, optional
        - A location into which the result is stored
        - If provided, it must have a shape that inputs broadcast to
        - If not provided or None, a freshly-allocated array is returned
        - A tuple (possible only as a keyword argument) must have the length equal to the number of outputs
    - `where` : array_like, optional
        - This condition is broadcast over the input
        - At locations where the condition is True, the `out` array will be set to the ufunc result
        - Elsewhere, the `out` will retain its original value
        - Note that if an uninitialized `out` array is created via the default ``out=None``, locations within it where the condition is False will remain uninitialized

In [42]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray
print(logical_not(a1 > 10))

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True
[False  True  True  True  True]
[ True  True  True  True  True]
[ True False False False False]


- `logical_xor(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`
    - Compute the truth value of `x1` XOR `x2`, element-wise.
    - returns `y` : bool or ndarray of bool
        - Boolean result of the logical XOR operation applied to the elements
    of `x1` and `x2`; the shape is determined by broadcasting.
        - This is a scalar if both `x1` and `x2` are scalars
    - `x1`, `x2` : array_like
        - Logical XOR is applied to the elements of `x1` and `x2`.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
    - `out` : ndarray, None, or tuple of ndarray and None, optional
        - A location into which the result is stored. If provided, it must have a shape that the inputs broadcast to.
        - If not provided or None, a freshly-allocated array is returned.
        - A tuple (possible only as a keyword argument) must have length equal to the number of outputs.
    - `where` : array_like, optional
        - This condition is broadcast over the input.
        - At locations where the condition is True, the `out` array will be set to the ufunc result.
        - Elsewhere, the `out` array will retain its original value.
        - Note that if an uninitialized `out` array is created via the default ``out=None``, locations within it where the condition is False will remain uninitialized.

In [43]:
from numpy import *

a1 = array([10, 30, 50, 70, 100])
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray
print(logical_not(a1 > 10))
print(logical_xor(a1 > 10, a1 < 101))

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
True
False
True
True
[False  True  True  True  True]
[ True  True  True  True  True]
[ True False False False False]
[ True False False False False]


- `numpy.where(condition, [x, y], /)`
    - return elements chosen from `x` or `y` depending on `condition`
    - can be used as a ternary operator to filter elements from two arrays based on a condition
    - returns `out` : ndarray
        - An array with elements from `x` where `condition` is True, and elements from `y` elsewhere.
    - .. note::
        - When only `condition` is provided, this function is a shorthand for ``np.asarray(condition).nonzero()``.
        - Using `nonzero` directly should be preferred, as it behaves correctly for subclasses.
        - The rest of this documentation covers only the case where all three arguments are provided.
    - `condition` : array_like, bool
        - Where True, yield `x`, otherwise yield `y`.
    - `x`, `y` : array_like
        - Values from which to choose. `x`, `y` and `condition` need to be broadcastable to some shape.

In [44]:
from numpy import *

a1 = array([1, 2, 3, 4, 5]) # changed all elements
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray
print(logical_not(a1 > 10))
print(logical_xor(a1 > 10, a1 < 101))

print(where(a1 % 2 != 0, a1, 0)) # only odd numbers seen, even numbers are replaced by 0

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
False
False
True
True
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ True  True  True  True  True]
[1 0 3 0 5]


In [45]:
from numpy import *

a1 = array([22, 2, 3, 4, 5]) # changed element
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray
print(logical_not(a1 > 10))
print(logical_xor(a1 > 10, a1 < 101))

print(where(a1 % 2 != 0, a1, 0)) # only odd numbers seen, even numbers are replaced by 0
print(where(a1 > a2, a1, a2)) # returns a1 element if greater, otherwise element from a2

[ True False False False False]
[False  True  True  True  True]
[ True False False False False]
True
False
True
False
[ True False False False False]
[ True  True  True  True  True]
[False  True  True  True  True]
[False  True  True  True  True]
[0 0 3 0 5]
[ 22  40  60  80 100]


In [46]:
from numpy import *

a1 = array([22, 2, 3, 4, 5]) # changed element
a2 = array([20, 40, 60, 80, 100])

print(a1 > a2)
print(a1 < a2)
print(a1 >= a2)

print(any(a1 >= a2)) # does logical OR comparison
print(all(a1 >= a2)) # does logical AND comparison
print(any(a1 <= a2))
print(all(a1 <= a2))

print(logical_and(a1 > 10, a1 < 101)) # check multiple logical conditions with logical AND on elements of ndarray
print(logical_or(a1 > 10, a1 < 101)) # check multiple logical conditions with logical OR on elements of ndarray
print(logical_not(a1 > 10))
print(logical_xor(a1 > 10, a1 < 101))

print(where(a1 % 2 != 0, a1, 0)) # only odd numbers seen, even numbers are replaced by 0
print(where(a1 > a2, a1, a2)) # returns a1 element if greater, otherwise element from a2
print(where(a1 > a2, a1, 0)) # returns a1 element if greater, otherwise 0

[ True False False False False]
[False  True  True  True  True]
[ True False False False False]
True
False
True
False
[ True False False False False]
[ True  True  True  True  True]
[False  True  True  True  True]
[False  True  True  True  True]
[0 0 3 0 5]
[ 22  40  60  80 100]
[22  0  0  0  0]


## 293. Copying  arrays
- You'll learn how to use arrays' copy and view functions, to do shallow copy and deep copy
- `numpy.ndarray.view([dtype][, type])`
    - `a.view([dtype][, type])`
    - New view of array with the same data
    - creates a shallow copy of the array, so changes in one array are reflected in other array
    - .. note::
        - Passing None for ``dtype`` is different from omitting the parameter, since the former invokes ``dtype(None)`` which is an alias for ``dtype('float_')``.
    - `dtype` : data-type or ndarray sub-class, optional
        - data-type descriptor of the returned view, e.g., float32 or int16.
        - Omitting it results in the view having the same data-type as `a`.
        - This argument can also be specified as an ndarray sub-class, which then specifies the type of the returned object (this is equivalent to setting the ``type`` parameter).
    - `type` : Python type, optional
        - Type of the returned view, e.g., ndarray or matrix.
        - Again, omission of the parameter results in type preservation.


In [47]:
# arraycopy.py
from numpy import *

a1 = arange(1, 10)
a2 = a1.view() # creates a shallow copy

print('a1:', a1)
print('a2:', a2)

a2[3] = 40 # due to shallow copy, changes reflect in a2 as well as a1
print('after modification')
print('a1:', a1)
print('a2:', a2)

a1: [1 2 3 4 5 6 7 8 9]
a2: [1 2 3 4 5 6 7 8 9]
after modification
a1: [ 1  2  3 40  5  6  7  8  9]
a2: [ 1  2  3 40  5  6  7  8  9]


- `numpy.ndarray.copy(order='C')`
    - `a.copy(order='C')`
    - returns a copy of the array
    - creates a deep copy of the array, so changes in one array are not reflected in other array
    - `order` : {'C', 'F', 'A', 'K'}, optional
        - Controls the memory layout of the copy. 'C' means C-order, 'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous, 'C' otherwise.
        - 'K' means match the layout of `a` as closely as possible.
        - (Note that this function and :func:`numpy.copy` are very similar but have different default values for their `order=arguments`, and this function always passes sub-classes through.)

In [48]:
from numpy import *

a1 = arange(1, 10)
a2 = a1.copy() # creates a shallow copy

print('a1:', a1)
print('a2:', a2)

a2[3] = 40 # due to deep copy, changes reflect in a2 only
print('after modification')
print('a1:', a1)
print('a2:', a2)

a1: [1 2 3 4 5 6 7 8 9]
a2: [1 2 3 4 5 6 7 8 9]
after modification
a1: [1 2 3 4 5 6 7 8 9]
a2: [ 1  2  3 40  5  6  7  8  9]


## 294. Slicing
- You'll see slicing in action on NumPy arrays
- `a[start, stop]` : starts from start index and stops at stop-1 index
- `a[start, stop, step]` : starts from start index and stops at stop-1 index with step
- `a[start:]` : starts from start index and goes till last element

In [49]:
# slicing.py
from numpy import *

a1 = arange(3, 12)
print(a1)
print(a1[3:7]) # starts from 3rd index , stops at (7-1) 6th index
print(a1[1:9:2]) # starts from 1st index , stops at (9-1) 8th index, with step of 2
print(a1[4:]) # starts from 4th index, goes till last element

[ 3  4  5  6  7  8  9 10 11]
[6 7 8 9]
[ 4  6  8 10]
[ 7  8  9 10 11]


## 295. Multidimensional arrays
- You'll learn how to create multidimensional arrays, and we'll explore one attribute on it
- `numpy.ndarray.ndim`
    - property of `numpy.ndarray` thar automatically stores the number of dimensions that an ndarray has

In [50]:
# multidimensional.py
from numpy import *

a1 = array([1, 2, 3, 4, 5, 6])
# print("DEBUG:", type(a1)) # debug
a2 = array([[1, 2, 3], [4, 5, 6]])
# print("DEBUG:", type(a2)) # debug
a3 = array([[[1, 2], [3, 4] ],  [[5, 6], [7, 8] ]])
# print("DEBUG:", type(a3)) # debug

print("a1:", a1) # prints single-dimensional array
print("a2:", a2) # prints two-dimensional array with two-rows, each row has three columns
print("a3:", a3) # prints three-dimensional array with 2 two-dimensional arrays

print("a1 ndim:", a1.ndim) # prints dimensions in a1 using property numpy.ndarray.ndim
print("a2 ndim:", a2.ndim) # prints dimensions in a2 using property numpy.ndarray.ndim
print("a3 ndim:", a3.ndim) # prints dimensions in a3 using property numpy.ndarray.ndim

a1: [1 2 3 4 5 6]
a2: [[1 2 3]
 [4 5 6]]
a3: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
a1 ndim: 1
a2 ndim: 2
a3 ndim: 3


## 296. Few more attributes
- Lets explore few more attributes of `ndarray`
- `numpy.ndarray.shape`
    - gives us the number of elements in the array in each dimension
    - shape property is usually used to get the current shape of an array but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it.
    - As with `numpy.reshape`, one of the new shape dimensions can be -1, in which case its value is inferred from the size of the array and the remaining dimensions
    - Reshaping an array in-place will fail if a copy is required.
    - `.. warning::`
    - Setting ``arr.shape`` is discouraged and may be deprecated in the future.
    - Using `ndarray.reshape` is the preferred approach.
- `numpy.ndarray.size`
    - gives the total size of the array, or the total number of elements
    - returns `element_count` : int, Number of elements in the array
- `numpy.ndarray.itemsize`
    - Length of one array element in bytes.
    - by default it uses `int32` for integer types, so returns 4 bytes
- `numpy.ndarray.dtype`
    - Data-type of the array's elements.
    - returns `d` : numpy dtype object
- `numpy.ndarray.nbytes`
    - Total bytes consumed by the elements of the array.

In [51]:
# multidimensional.py
from numpy import *

a1 = array([1, 2, 3, 4, 5, 6])
a2 = array([[1, 2, 3], [4, 5, 6]])
a3 = array([[[1, 2], [3, 4] ],  [[5, 6], [7, 8] ]])

print("a1:", a1) # prints single-dimensional array
print("a2:", a2) # prints two-dimensional array with two-rows, each row has three columns
print("a3:", a3) # prints three-dimensional array with 2 two-dimensional arrays

print("a1 ndim:", a1.ndim) # prints dimensions in a1 using property numpy.ndarray.ndim
print("a2 ndim:", a2.ndim) # prints dimensions in a2 using property numpy.ndarray.ndim
print("a3 ndim:", a3.ndim) # prints dimensions in a3 using property numpy.ndarray.ndim

print("a1 shape:", a1.shape) # prints shape of a1 using property numpy.ndarray.shape
print("a2 shape:", a2.shape) # prints shape of a2 using property numpy.ndarray.shape
print("a3 shape:", a3.shape) # prints shape of a3 using property numpy.ndarray.shape

a2.shape = (3, 2) # change shape from (2, 3) to (3, 2)      # discouraged to use
a2.reshape((3, 2))      # ndarray.reshape() method
# reshape(a2, (3, 2))   # numpy.reshape() method
print("a2:", a2)

print("a1 size:", a1.size) # prints size of a1 using property numpy.ndarray.size
print("a2 size:", a2.size) # prints size of a2 using property numpy.ndarray.size
print("a3 size:", a3.size) # prints size of a3 using property numpy.ndarray.size

print("a1 itemsize:", a1.itemsize) # prints length of one array element of a1 using property numpy.ndarray.itemsize
print("a2 itemsize:", a2.itemsize) # prints length of one array element of a2 using property numpy.ndarray.itemsize
print("a3 itemsize:", a3.itemsize) # prints length of one array element of a3 using property numpy.ndarray.itemsize

print("a1 dtype:", a1.dtype) # prints dtype of a1 using property numpy.ndarray.dtype
print("a2 dtype:", a2.dtype) # prints dtype of a2 using property numpy.ndarray.dtype
print("a3 dtype:", a3.dtype) # prints dtype of a3 using property numpy.ndarray.dtype

print("a1 nbytes:", a1.nbytes) # prints total bytes consumed by all elements of a1 using property numpy.ndarray.nbytes
print("a2 nbytes:", a2.nbytes) # prints total bytes consumed by all elements of a2 using property numpy.ndarray.nbytes
print("a3 nbytes:", a3.nbytes) # prints total bytes consumed by all elements of a3 using property numpy.ndarray.nbytes


a1: [1 2 3 4 5 6]
a2: [[1 2 3]
 [4 5 6]]
a3: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
a1 ndim: 1
a2 ndim: 2
a3 ndim: 3
a1 shape: (6,)
a2 shape: (2, 3)
a3 shape: (2, 2, 2)
a2: [[1 2]
 [3 4]
 [5 6]]
a1 size: 6
a2 size: 6
a3 size: 8
a1 itemsize: 4
a2 itemsize: 4
a3 itemsize: 4
a1 dtype: int32
a2 dtype: int32
a3 dtype: int32
a1 nbytes: 24
a2 nbytes: 24
a3 nbytes: 32


## 297. Few more functions
- You'll learn a few more functions that can be applied to single and multidimensional arrays
- `numpy.ndarray.reshape(shape, order='C')`
    - `a.reshape(shape, order='C')`
    - Returns an array containing the same data with a new shape.
    - Unlike the free function `numpy.reshape`, this method on `ndarray` allows the elements of the shape parameter to be passed in as separate arguments.
    - For example, ``a.reshape(10, 11)`` is equivalent to ``a.reshape((10, 11))``
- `numpy.reshape(a, newshape, order='C')`
    - Gives a new shape to an array without changing its data.
    - returns `reshaped_array` : ndarray
        - This will be a new view object if possible; otherwise, it will be a copy.
        - Note there is no guarantee of the *memory layout* (C- or Fortran- contiguous) of the returned array.
    - `ndarray.reshape` : Equivalent method.
- `numpy.ndarray.flatten(order='C')`
    - convert a multidimensional array into a single-dimensional array
    - return a copy of the array collapsed into one-dimension
    - returns `y` : ndarray
        - A copy of the input array, flattened to one dimension
    - `order` : {'C', 'F', 'A', 'K'}, optional
        - 'C' means to flatten in row-major (C-style) order.
        - 'F' means to flatten in column-major (Fortran-style) order.
        - 'A' means to flatten in column-major order if `a` is Fortran *contiguous* in memory, row-major order otherwise. 'K' means to flatten `a` in the order the elements occur in memory.
        - The default is 'C'.
- `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)`
    - helpful when you're working with matrices
    - return a 2-D array with ones on the diagonal and zeros elsewhere
    - `N` : int
        - Number of rows in the output.
    - `M` : int, optional
        - Number of columns in the output. If None, defaults to `N`.
    - `k` : int, optional
        - Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    - `dtype` : data-type, optional
        - Data-type of the returned array.
    - `order` : {'C', 'F'}, optional
        - Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

In [52]:
# arrayFunctions.py
from numpy import *

a1 = arange(12)
print('a1:\n', a1)

a2 = reshape(a1, (2, 6))
print("a2:\n", a2)

a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [53]:
from numpy import *

a1 = arange(12)
print('a1:\n', a1)

a2 = reshape(a1, (2, 7)) # gives an error as ndarray size does not match
print("a2:\n", a2)

a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (2,7)

In [54]:
from numpy import *

a1 = arange(12)
print('a1:\n', a1)

a2 = reshape(a1, (4, 3)) # reshapes with 4 rows 4 cols
print("a2:\n", a2)

a3 = reshape(a1, (2, 2, 3)) # reshapes into 2 two-dimensional arrays
print("a3:\n", a3)

print("a3.flatten():\n", a3.flatten()) # returns a 1-D array

print("numpy.eye(3):\n", eye(3)) # return a 2-D array with ones at diagonal
print("numpy.eye(3):\n", eye(2))

print("ones (2, 3) :\n", ones((2, 3))) # returns ndarray filled with ones in specified shape, default dtype=float64
print("ones (2, 3) in int :\n", ones((2, 3), int)) # returns ndarray filled with ones in specified shape

print("zeros (2, 3) :\n", zeros((2, 3))) # returns ndarray filled with zeros in specified shape, default dtype=float64
print("zeros (2, 3) in int :\n", zeros((2, 3), int)) # returns ndarray filled with zeros in specified shape


a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
a3.flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
numpy.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
numpy.eye(3):
 [[1. 0.]
 [0. 1.]]
ones (2, 3) :
 [[1. 1. 1.]
 [1. 1. 1.]]
ones (2, 3) in int :
 [[1 1 1]
 [1 1 1]]
zeros (2, 3) :
 [[0. 0. 0.]
 [0. 0. 0.]]
zeros (2, 3) in int :
 [[0 0 0]
 [0 0 0]]
