## 287. Introduction
- You'll learn and use `NumPy` module
- NumPy comes with various in-built classes and functions that will help us do calculations and also manipulate single-dimensional arrays as well as multi-dimensional arrays
- All the elements in a NumPy array are of same type
- To use the NumPy module, we install it first and then we simply import NumPy, and start using it
- We'll create arrays using various functions that NumPy provides like `array()`, `linspace()`, `logspace()`, `arange()`, `zeros()`, `ones()`, and more
- And, then we'll also use various mathematical opertations that are in-built into NumPy
- This will help you do various scientific calculations as well
- We'll also compare arrays, do array copying, slicing of arrays, deal with multi-dimensional arrays, matrics and much more
- Once you are aware of all these, you can learn other things in NumPy as required for your projects

## 288. NumPy in action
- You'll learn how to work with arrays using the NumPy package
- `numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`
    - Creates an array
    - returns ndarray, an array object satisfying the specified requirements
    - `object` : array-like, an array, any object exposing the array interface, an object whose ``__array__`` method returns an array or any (nested) sequence. If object is a scalar, a 0-dimensional array containing object is returned
    - `dtype` : datatype, optional, the desired data-type for the array. If not given, NumPy will try to use a default ``dtype`` that can represent the values (by applying promotion rules when necessary)
    -

In [2]:
# numpyinaction
# arrays.py
import numpy

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
print(arr)

[1 2 3 4 5]


In [7]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
carr = array(['a', 'b', 'c']) # character arrray
print(arr)
print(carr)

[1 2 3 4 5]
['a' 'b' 'c']


In [9]:
from numpy import *

arr = array([1, 2, 3, 4, 5]) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest']) # string array
print(arr)
print(carr)
print(sarr)

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']


In [10]:
from numpy import *

arr = array([1, 2, 3, 4, 5], int) # number array
carr = array(['a', 'b', 'c']) # character arrray
sarr = array(['Python', 'Django', 'Django Rest'], dtype=str) # string array
print(arr)
print(carr)
print(sarr)

[1 2 3 4 5]
['a' 'b' 'c']
['Python' 'Django' 'Django Rest']


## 289. linspace logspace and more
-